import 'package:flutter/material.dart';
import 'package:flutterapp/planieapp/generateddaftarwidget/generated/GeneratedLine3Widget.dart';
import 'package:flutterapp/planieapp/generateddaftarwidget/generated/GeneratedMayaBaruicononly2Widget2.dart';
import 'package:flutterapp/planieapp/generateddaftarwidget/generated/GeneratedSudahPunyaAkunWidget.dart';
import 'package:flutterapp/planieapp/generateddaftarwidget/generated/GeneratedComponent5Widget.dart';
import 'package:flutterapp/planieapp/generateddaftarwidget/generated/GeneratedKetikUlangPasswordWidget.dart';
import 'package:flutterapp/planieapp/generateddaftarwidget/generated/GeneratedMasukkanUlangPasswordWidget.dart';
import 'package:flutterapp/planieapp/generateddaftarwidget/generated/GeneratedMASUKWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/planieapp/generateddaftarwidget/generated/GeneratedComponent4Widget.dart';
import 'package:flutterapp/planieapp/generateddaftarwidget/generated/GeneratedRectangle1Widget1.dart';
import 'package:flutterapp/planieapp/generateddaftarwidget/generated/GeneratedLogoPlanieWidget3.dart';

/* Frame Daftar
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDaftarWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 244, 244, 179),
                ),
              ),
              Positioned(
                left: 111.0,
                top: 23.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 144.0,
                child: GeneratedMayaBaruicononly2Widget2(),
              ),
              Positioned(
                left: 125.0,
                top: 454.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 17.0,
                child: GeneratedSudahPunyaAkunWidget(),
              ),
              Positioned(
                left: 53.0,
                top: 335.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 17.0,
                child: GeneratedKetikUlangPasswordWidget(),
              ),
              Positioned(
                left: 54.0,
                top: 215.0,
                right: null,
                bottom: null,
                width: 258.0,
                height: 45.0,
                child: GeneratedComponent4Widget(),
              ),
              Positioned(
                left: 54.0,
                top: 277.0,
                right: null,
                bottom: null,
                width: 258.0,
                height: 41.0,
                child: GeneratedComponent5Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.5416666666666666;

                  final double height = constraints.maxHeight * 0.0328125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.15555555555555556,
                        y: constraints.maxHeight * 0.5546875,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedMasukkanUlangPasswordWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 54.0,
                top: 404.0,
                right: null,
                bottom: null,
                width: 257.0,
                height: 32.0,
                child: GeneratedRectangle1Widget1(),
              ),
              Positioned(
                left: 152.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 24.0,
                child: GeneratedMASUKWidget(),
              ),
              Positioned(
                left: 140.0,
                top: 558.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 21.0,
                child: GeneratedLogoPlanieWidget3(),
              ),
              Positioned(
                left: 55.0,
                top: 381.0,
                right: null,
                bottom: null,
                width: 256.0,
                height: 1.0,
                child: GeneratedLine3Widget(),
              )
            ]),
      ),
    ));
  }
}
