import 'package:flutter/material.dart';
import 'package:flutterapp/planieapp/generatedverifikasiwidget/generated/GeneratedMayaBaruicononly3Widget.dart';
import 'package:flutterapp/planieapp/generatedverifikasiwidget/generated/GeneratedLogoPlanieWidget4.dart';
import 'package:flutterapp/planieapp/generatedverifikasiwidget/generated/GeneratedKIRIMKODEOTPWidget.dart';
import 'package:flutterapp/planieapp/generatedverifikasiwidget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/planieapp/generatedverifikasiwidget/generated/GeneratedComponent6Widget.dart';

/* Frame verifikasi
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVerifikasiWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 244, 244, 179),
                ),
              ),
              Positioned(
                left: 51.0,
                top: 213.0,
                right: null,
                bottom: null,
                width: 258.0,
                height: 45.0,
                child: GeneratedComponent6Widget(),
              ),
              Positioned(
                left: 112.0,
                top: 26.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 144.0,
                child: GeneratedMayaBaruicononly3Widget(),
              ),
              Positioned(
                left: 51.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 258.0,
                height: 32.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 119.0,
                top: 284.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 21.0,
                child: GeneratedKIRIMKODEOTPWidget(),
              ),
              Positioned(
                left: 141.0,
                top: 557.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 21.0,
                child: GeneratedLogoPlanieWidget4(),
              )
            ]),
      ),
    ));
  }
}
