import 'package:flutter/material.dart';
import 'package:flutterapp/planieapp/generatedmasukwidget/generated/GeneratedComponent3Widget.dart';
import 'package:flutterapp/planieapp/generatedmasukwidget/generated/GeneratedLogoPlanieWidget1.dart';
import 'package:flutterapp/planieapp/generatedmasukwidget/generated/GeneratedBelumPunyaAkunWidget.dart';
import 'package:flutterapp/planieapp/generatedmasukwidget/generated/GeneratedMayaBaruicononly2Widget.dart';
import 'package:flutterapp/planieapp/generatedmasukwidget/generated/GeneratedComponent2Widget.dart';
import 'package:flutterapp/planieapp/generatedmasukwidget/generated/GeneratedLupaPasswordWidget.dart';
import 'package:flutterapp/planieapp/generatedmasukwidget/generated/GeneratedComponent1Widget.dart';

/* Frame Masuk
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMasukWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 244, 244, 179),
                ),
              ),
              Positioned(
                left: 111.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 144.0,
                child: GeneratedMayaBaruicononly2Widget(),
              ),
              Positioned(
                left: 132.0,
                top: 419.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 17.0,
                child: GeneratedLupaPasswordWidget(),
              ),
              Positioned(
                left: 125.0,
                top: 400.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 17.0,
                child: GeneratedBelumPunyaAkunWidget(),
              ),
              Positioned(
                left: 53.0,
                top: 217.0,
                right: null,
                bottom: null,
                width: 258.0,
                height: 44.0,
                child: GeneratedComponent1Widget(),
              ),
              Positioned(
                left: 53.0,
                top: 275.0,
                right: null,
                bottom: null,
                width: 258.0,
                height: 45.0,
                child: GeneratedComponent2Widget(),
              ),
              Positioned(
                left: 53.0,
                top: 344.0,
                right: null,
                bottom: null,
                width: 257.0,
                height: 32.0,
                child: GeneratedComponent3Widget(),
              ),
              Positioned(
                left: 140.0,
                top: 558.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 21.0,
                child: GeneratedLogoPlanieWidget1(),
              )
            ]),
      ),
    ));
  }
}
