import 'package:flutter/material.dart';
import 'package:flutterapp/planieapp/generatedlogowidget/generated/GeneratedMayaBaruicononly1Widget.dart';
import 'package:flutterapp/planieapp/generatedlogowidget/generated/GeneratedLogoPlanieWidget.dart';

/* Frame Logo
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLogoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 244, 244, 179),
                ),
              ),
              Positioned(
                left: 45.0,
                top: 359.0,
                right: null,
                bottom: null,
                width: 270.0,
                height: 111.0,
                child: GeneratedLogoPlanieWidget(),
              ),
              Positioned(
                left: 74.0,
                top: 144.0,
                right: null,
                bottom: null,
                width: 212.0,
                height: 215.0,
                child: GeneratedMayaBaruicononly1Widget(),
              )
            ]),
      ),
    ));
  }
}
