import 'package:flutter/material.dart';
import 'package:flutterapp/planieapp/generatedotpwidget/generated/GeneratedRectangle2Widget1.dart';
import 'package:flutterapp/planieapp/generatedotpwidget/generated/GeneratedKIRIMWidget.dart';
import 'package:flutterapp/planieapp/generatedotpwidget/generated/GeneratedComponent6Widget1.dart';
import 'package:flutterapp/planieapp/generatedotpwidget/generated/GeneratedMayaBaruicononly3Widget1.dart';
import 'package:flutterapp/planieapp/generatedotpwidget/generated/GeneratedLogoPlanieWidget5.dart';

/* Frame otp
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOtpWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 244, 244, 179),
                ),
              ),
              Positioned(
                left: 51.0,
                top: 213.0,
                right: null,
                bottom: null,
                width: 258.0,
                height: 45.0,
                child: GeneratedComponent6Widget1(),
              ),
              Positioned(
                left: 112.0,
                top: 26.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 144.0,
                child: GeneratedMayaBaruicononly3Widget1(),
              ),
              Positioned(
                left: 51.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 258.0,
                height: 32.0,
                child: GeneratedRectangle2Widget1(),
              ),
              Positioned(
                left: 158.0,
                top: 282.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 24.0,
                child: GeneratedKIRIMWidget(),
              ),
              Positioned(
                left: 141.0,
                top: 557.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 21.0,
                child: GeneratedLogoPlanieWidget5(),
              )
            ]),
      ),
    ));
  }
}
