import 'package:flutter/material.dart';
import 'package:flutterapp/planieapp/generatedmasukwidget2/generated/GeneratedComponent1Widget1.dart';
import 'package:flutterapp/planieapp/generatedmasukwidget2/generated/GeneratedLogoPlanieWidget2.dart';
import 'package:flutterapp/planieapp/generatedmasukwidget2/generated/GeneratedComponent2Widget1.dart';
import 'package:flutterapp/planieapp/generatedmasukwidget2/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/planieapp/generatedmasukwidget2/generated/GeneratedUBAHPASSWORDWidget.dart';
import 'package:flutterapp/planieapp/generatedmasukwidget2/generated/GeneratedMayaBaruicononly2Widget1.dart';

/* Frame Masuk
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMasukWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 244, 244, 179),
                ),
              ),
              Positioned(
                left: 111.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 144.0,
                child: GeneratedMayaBaruicononly2Widget1(),
              ),
              Positioned(
                left: 53.0,
                top: 217.0,
                right: null,
                bottom: null,
                width: 258.0,
                height: 44.0,
                child: GeneratedComponent1Widget1(),
              ),
              Positioned(
                left: 53.0,
                top: 275.0,
                right: null,
                bottom: null,
                width: 258.0,
                height: 45.0,
                child: GeneratedComponent2Widget1(),
              ),
              Positioned(
                left: 140.0,
                top: 558.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 21.0,
                child: GeneratedLogoPlanieWidget2(),
              ),
              Positioned(
                left: 53.0,
                top: 339.0,
                right: null,
                bottom: null,
                width: 258.0,
                height: 32.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 113.0,
                top: 345.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 21.0,
                child: GeneratedUBAHPASSWORDWidget(),
              )
            ]),
      ),
    ));
  }
}
